spring:
  cloud:
    gateway:
      routes:
      - id: manageCurrConversionFactorms
        uri: lb://manageCurrConversionFactorms
        predicates:
        - Path=/currencyfactor/**
        
      - id: currencyConversionms
        uri: lb://manageCurrConversionFactorms
        predicates:
        - Path=/currencyconverter/**
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:
  port: 9081

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${apigateway.eureka.url:http://localhost:8761/eureka}